# Custom site.* metadata
logo: /assets/images/moonray-logo.svg
description: Documentation

exclude: [ style-reference ]

collections_dir: .

sass:
  sourcemap: never

url: https://dreamworksanimation.github.io
BASE_PATH : https://openmoonray.org/openmoonray-docs/
repository: https://github.com/OpenMoonRay/openmoonray-docs/

permalink: pretty

collections:

  cameras:
    permalink: /:collection/:name
    output: true

  light-filters:
    permalink: /:collection/:name
    output: true
    order:
      -Decay-Light-Filter.md
      -Cookie-Light-Filter.md
      -Barn-Door-Light-Filter.md

  lights:
    permalink: /:collection/:name
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
